### ISSUE TITLE
Custom comparator unsafe re-entry

### ISSUE THREAD

**Issue by gbrsales** [kim/leveldb-haskell#27]
Working with a custom comparator I get the following error, which also causes a segfault:

```
comparator: schedule: re-entered unsafely.
   Perhaps a 'foreign import unsafe' should be 'safe'?
```

I'm using GHC 7.8.4 and leveldb-haskell 0.6.1.

The following code (slightly modified from the example "comparator.hs") is sufficient to display the issue:

```haskell
{-# LANGUAGE OverloadedStrings #-}

-- | Demo custom comparator

module Main where

import           Control.Monad
import           Control.Monad.IO.Class     (liftIO)
import qualified Data.ByteString.Char8      as B
import           Data.Default
import           Database.LevelDB
import qualified Database.LevelDB.Streaming as S


customComparator :: Comparator
customComparator = Comparator compare

main :: IO ()
main = runResourceT $ do
    db <- open "/tmp/lvlcmptest"
               defaultOptions{ createIfMissing = True
                             , comparator = Just customComparator
                             }

    forM_ [1..1000000::Int] $ \i -> do
        put db def (B.pack $ "zzz" ++ show i) ""

    withIterator db def $ \iter -> liftIO $
            S.toList (S.entrySlice iter S.AllKeys S.Asc)
        >>= print

    return ()
```

The problem only manifests itself when I issue a large number of puts in rapid succession.

Do you have any idea about what could be causing this?

**Comment by kim** [comment]
I think what's happening is that the native leveldb is calling back into Haskell (ie. the comparator function) from _a different thread_, which the RTS is able to [detect](https://github.com/ghc/ghc/blob/ghc-7.8/rts/Schedule.c#L205-L207). Try linking the program against the threaded runtime (ie. `ghc --make -threaded`) and let me know if that works for you.

**Comment by kim** [comment]
And yeah, the error message is quite unhelpful as all (relevant) `foreign import`s _are_ imported `safe` -- yet we need the threaded RTS to make C callbacks actually safe.

**Comment by gbrsales** [comment]
Yes, enabling the threaded runtime fixes the issue. Thanks!
