### ISSUE TITLE
Please add support for QuickCheck 2.8

### ISSUE THREAD

**Issue by peti** [kim/leveldb-haskell#28]
We've updated to QuickCheck 2.8 in NixOS, but unfortunately this means that we can no longer run the leveldb-haskell test suite: http://packdeps.haskellers.com/feed?needle=leveldb-haskell.

**Comment by kim** [comment]
Pushed out the [recent changes](https://github.com/kim/leveldb-haskell/compare/v0.6.2...v0.6.3) to hackage. Hope it won't bite me for no upper bounds later :open_mouth:

**Comment by kim** [comment]
Please reopen if there are still issues

**Comment by kim** [comment]
Also, is there a way to somehow subscribe to `nixpgs` build failures for just a specific package?
