### ISSUE TITLE
Handle finalizer can run too soon

### ISSUE THREAD

**Issue by facundominguez** [kim/leveldb-haskell#29]
leveldb-haskell puts a finalizer on the leveldb handle. This makes the pattern `open-leveldb-handle >>= \h -> get-leveldb-iterator h >>= \it -> use it` work most of the time, except when the GC happens to run before `use it` completes evaluation.

How about `Iterator` retains a reference to the handle so the user doesn't need to be aware of this?

**Comment by kim** [comment]
Aww, really? Is this reproducible, eg by calling `performGC` after the second bind? Your proposal seems reasonable, but I'd like to verify it somehow.

Meanwhile, have you considered using the `ResourceT`-based API? It doesn't have these kinds of problems.

**Comment by facundominguez** [comment]
```Haskell
import Control.Concurrent
import Control.Monad
import Database.LevelDB.Base
import System.Mem

main :: IO ()
main = do
  db <- open "test.db" defaultOptions { createIfMissing = True }
  withIter db defaultReadOptions { fillCache = False } $ \_ ->
    replicateM_ 10 $ do
      threadDelay 100000
      performMajorGC
```
fails with
```
pthread lock: Invalid argument
Aborted (core dumped)
```

My workaround for now is to close the handle explicitly.

**Comment by kim** [comment]
Thanks. It seems the proposed solution fixes the issue. However, the trick doesn't work for `Snapshot`s, to which the issue applies as well (that is, unless `withSnapshot` is used). This makes me think that to prevent finalizers from being run prematurely, it is really only safe to rely on `bracket` (which uses `mask` under the hood), ie. the various `with*` combinators provided by the library.

I'll need to dig a bit further.

**Comment by kim** [comment]
So this is the only solution I could come up with. The downside is of course that the `db` pointer may never actually be free'd when relying solely on the GC to free handles acquired from the native library. It is also a bit of a pity to introduce another refcounting scheme, where `ResourceT` already solves the problem -- yet people don't seem to like it.

@facundominguez could you confirm this fixes the issue for you? Or provide an alternative solution?

**Comment by facundominguez** [comment]
If you want to keep things simple, there is always the choice of not using finalizers and expose the user to leaking the handle if he doesn't use `bracket` or `ResourceT`.

In my particular case, I'm not using `ResourceT` because `withDB` sufficed where I really cared of leaks.

> could you confirm this fixes the issue for you? 

Works for me.
