### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by yairchu** [kim/leveldb-haskell#36]
<img width="520" alt="screen shot 2018-06-01 at 13 41 35" src="https://user-images.githubusercontent.com/97606/40836999-86da7d30-65a1-11e8-993a-b6c80c3c41de.png">

The link http://leveldb.googlecode.com is broken. Perhaps https://github.com/google/leveldb is the up-to-date link?

**Comment by kim** [comment]
Updated. Thanks.
